### ISSUE TITLE
Runtime exception detected

### ISSUE THREAD

**Issue by Ikura9** [Moderpach/Extinguish#5]
java.lang.NoSuchMethodException: getInternalDisplayToken []
	at java.lang.Class.getMethod(Class.java:2068)
	at java.lang.Class.getMethod(Class.java:1690)
	at d6.a.b(Unknown Source:114)
	at h6.l.getValue(Unknown Source:20)
	at u4.i.d(Unknown Source:2)
	at extinguish.shizuku_service.DisplayControlService.j(Unknown Source:51)
	at f6.b.onTransact(Unknown Source:144)
	at android.os.Binder.execTransact(Binder.java:675)
---null

This happens you when I try to turn screen of using any of the 2 solutions

Edit: device Huawei mate 10 lite, Android 8.0

**Comment by Moderpach** [comment]
New version won't release soon.
You can try https://github.com/Moderpach/Extinguish/actions/runs/10880869259 to see whether it solved
